### ISSUE TITLE
4 Errors while running the front end 

### ISSUE THREAD

**Issue by Jihen-Regaya** [lmanukyan/print-designer#6]
when i run the command yarn dev:app in git bash i get these 4 errors and I couldn't solve them. 

 ERROR in ./src/main.js
Module build failed: Error: Cannot find module 'C:\Users\jihen\print-designer\src\app\node_modules\quasar\dist\transforms\import-transformation.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1285:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1273:15)
    at resolveExports (node:internal/modules/cjs/loader:639:14)
    at Module._findPath (node:internal/modules/cjs/loader:747:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1234:27)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at getDevlandFile (C:\Users\jihen\print-designer\src\app\node_modules\vue-cli-plugin-quasar\lib\get-devland-file.js:3:13)
    at Object.<anonymous> (C:\Users\jihen\print-designer\src\app\node_modules\vue-cli-plugin-quasar\lib\loader.js.transform-quasar-imports.js:2:30)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:126:16)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\ProgressPlugin.js:457:9
    at Hook.eval [as call] (eval at create (C:\Users\jihen\print-designer\src\app\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\jihen\print-designer\src\app\node_modules\tapable\lib\Hook.js:14:14)
    at NormalModule._doBuild (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:944:24)
    at NormalModule.build (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:1144:15)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\Compilation.js:1418:12
    at NormalModule.needBuild (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:1466:32)
    at Compilation._buildModule (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\Compilation.js:1399:10)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:324:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\jihen\print-designer\src\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\jihen\print-designer\src\app\node_modules\tapable\lib\Hook.js:18:14)
    at AsyncQueue._startProcessing (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:314:26)
    at AsyncQueue._ensureProcessing (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:301:12)
    at process.processImmediate (node:internal/timers:491:21)

ERROR in ./node_modules/webpack-dev-server/client/index.js?protocol=ws&hostname=localhost&port=3040&pathname=%2Fws&logging=none&progress=true&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true
Module build failed (from ./node_modules/vue-cli-plugin-quasar/lib/loader.js.transform-quasar-imports.js):
Error: Cannot find module 'C:\Users\jihen\print-designer\src\app\node_modules\quasar\dist\transforms\import-transformation.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1285:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1273:15)
    at resolveExports (node:internal/modules/cjs/loader:639:14)
    at Module._findPath (node:internal/modules/cjs/loader:747:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1234:27)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at getDevlandFile (C:\Users\jihen\print-designer\src\app\node_modules\vue-cli-plugin-quasar\lib\get-devland-file.js:3:13)
    at Object.<anonymous> (C:\Users\jihen\print-designer\src\app\node_modules\vue-cli-plugin-quasar\lib\loader.js.transform-quasar-imports.js:2:30)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:126:16)
    at loadLoader (C:\Users\jihen\print-designer\src\app\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Users\jihen\print-designer\src\app\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\Users\jihen\print-designer\src\app\node_modules\loader-runner\lib\LoaderRunner.js:398:2)
    at NormalModule._doBuild (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:959:3)
    at NormalModule.build (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:1144:15)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\Compilation.js:1418:12
    at NormalModule.needBuild (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:1466:32)
    at Compilation._buildModule (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\Compilation.js:1399:10)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:324:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\jihen\print-designer\src\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:314:26)
    at AsyncQueue._ensureProcessing (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:301:12)
    at process.processImmediate (node:internal/timers:491:21)

ERROR in ./node_modules/webpack/hot/dev-server.js
Module build failed: Error: Cannot find module 'C:\Users\jihen\print-designer\src\app\node_modules\quasar\dist\transforms\import-transformation.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1285:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1273:15)
    at resolveExports (node:internal/modules/cjs/loader:639:14)
    at Module._findPath (node:internal/modules/cjs/loader:747:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1234:27)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at getDevlandFile (C:\Users\jihen\print-designer\src\app\node_modules\vue-cli-plugin-quasar\lib\get-devland-file.js:3:13)
    at Object.<anonymous> (C:\Users\jihen\print-designer\src\app\node_modules\vue-cli-plugin-quasar\lib\loader.js.transform-quasar-imports.js:2:30)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:126:16)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\ProgressPlugin.js:457:9
    at Hook.eval [as call] (eval at create (C:\Users\jihen\print-designer\src\app\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:9:1)
    at NormalModule._doBuild (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:944:24)
    at NormalModule.build (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:1144:15)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\Compilation.js:1418:12
    at NormalModule.needBuild (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:1466:32)
    at Compilation._buildModule (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\Compilation.js:1399:10)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:324:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\jihen\print-designer\src\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:314:26)
    at AsyncQueue._ensureProcessing (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:301:12)
    at process.processImmediate (node:internal/timers:491:21)

ERROR in ./node_modules/whatwg-fetch/fetch.js
Module build failed (from ./node_modules/vue-cli-plugin-quasar/lib/loader.js.transform-quasar-imports.js):
Error: Cannot find module 'C:\Users\jihen\print-designer\src\app\node_modules\quasar\dist\transforms\import-transformation.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1285:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1273:15)
    at resolveExports (node:internal/modules/cjs/loader:639:14)
    at Module._findPath (node:internal/modules/cjs/loader:747:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1234:27)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at getDevlandFile (C:\Users\jihen\print-designer\src\app\node_modules\vue-cli-plugin-quasar\lib\get-devland-file.js:3:13)
    at Object.<anonymous> (C:\Users\jihen\print-designer\src\app\node_modules\vue-cli-plugin-quasar\lib\loader.js.transform-quasar-imports.js:2:30)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:126:16)
    at loadLoader (C:\Users\jihen\print-designer\src\app\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Users\jihen\print-designer\src\app\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\Users\jihen\print-designer\src\app\node_modules\loader-runner\lib\LoaderRunner.js:398:2)
    at NormalModule._doBuild (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:959:3)
    at NormalModule.build (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:1144:15)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\Compilation.js:1418:12
    at NormalModule.needBuild (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\NormalModule.js:1466:32)
    at Compilation._buildModule (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\Compilation.js:1399:10)
    at C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:324:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\jihen\print-designer\src\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:314:26)
    at AsyncQueue._ensureProcessing (C:\Users\jihen\print-designer\src\app\node_modules\webpack\lib\util\AsyncQueue.js:301:12)
    at process.processImmediate (node:internal/timers:491:21)

**Comment by lmanukyan** [comment]
Hi @Jihen-Regaya 
Please update **vue-cli-plugin-quasar**

`cd src/app`
`yarn add vue-cli-plugin-quasar@5.1.0`
